[tool.poetry]
name = "livecoding"
version = "0.1.0"
description = ""
authors = ["0xb5951 <oxkeita@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
FoxDot = "^0.8.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
